name: coffee-shop

services:
  inventory-service:
    image: inventory-service
    container_name: inventory
    ports:
      - "3000:3000"
    networks:
      - coffee-shop-network
  order-service:
    image: order-service
    container_name: order
    ports:
      - "4000:4000"
    networks:
      - coffee-shop-network
    environment:
      INVENTORY_URL: http://inventory:3000
    depends_on:
      - inventory-service
networks:
  coffee-shop-network:
    driver: bridge
