apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: jeeturathore89/order-service:v1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: INVENTORY_URL
              value: "http://10.111.21.44:3000"